/*
 * TMAX FDL header file. automatically generated by fdlc
 * Field Table File : mem.f
 */



#define ID 	 ((FLDKEY)469762149) /* number: 101 type: string */ 
#define NAME 	 ((FLDKEY)469762150) /* number: 102 type: string */ 
#define DEPT 	 ((FLDKEY)469762151) /* number: 103 type: string */ 
